### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by ztszm** [jatin-cbs/Lutris-RHEL-CentOS-8#3]
[root@bogon Lutris-RHEL-CentOS-8]# dnf install lutris-0.5.2.1-1.el8.x86_64.rpm
Last metadata expiration check: 0:00:22 ago on Mon 06 Apr 2020 07:15:53 PM CST.
Error: 
 Problem: conflicting requests
  - nothing provides python3-PyYAML needed by lutris-0.5.2.1-1.el8.x86_64
  - nothing provides python3-evdev needed by lutris-0.5.2.1-1.el8.x86_64
  - nothing provides python3-gobject needed by lutris-0.5.2.1-1.el8.x86_64
  - nothing provides vulkan-loader needed by lutris-0.5.2.1-1.el8.x86_64
  - nothing provides vulkan-loader(x86-32) needed by lutris-0.5.2.1-1.el8.x86_64
  - nothing provides webkit2gtk3 needed by lutris-0.5.2.1-1.el8.x86_64

**Comment by Saladin1812** [comment]
@ztszm These dependencies are in RHEL/CentOS repositories you may try manually try installing the dependencies by sudo dnf install python3-PyYAML and so on.....  
Also ensure you have Powertools RPM Fusion (free and Non free) and EPEL repo enabled on CentOS and additional Code ready builder repo if you are on RHEL.

**Comment by Saladin1812** [comment]
Manually installing dependencies should probably fix this tho @ztszm

**Comment by ztszm** [comment]
thanks so much.It saved



发自我的iPhone


------------------ Original ------------------

**Comment by ztszm** [comment]
Thanks again
