### ISSUE TITLE
cabextract is in EPEL 8

### ISSUE THREAD

**Issue by robert-scheck** [jatin-cbs/Lutris-RHEL-CentOS-8#6]
cabextract is meanwhile in EPEL 8, see also: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2021-6d33b87c36

**Comment by Saladin1812** [comment]
Yes we have removed it from the install instruction on lutris website and also I have given a warning here.. I will remove cabextract completely soon.

The PR was merged https://github.com/lutris/website/pull/573

https://bugzilla.redhat.com/show_bug.cgi?id=1744725
